services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/src
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - db-store:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-store:
