services:
  backend:
    build:
      context: ./src/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./src:/app
    networks:
      - backend-network
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - db-store:/var/lib/postgresql/data
    networks:
      - backend-network
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
      - frontend-node-modules:/app/node_modules
      - frontend-public:/app/public

volumes:
  db-store:
  frontend-node-modules:
  frontend-public:

networks:
  backend-network:
    driver: bridge