services:
  backend:
    build:
      context: ./src/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./src:/app
    networks:
      - backend-network
  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - db-store:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  db-store:

networks:
  backend-network:
    driver: bridge